services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - COMPOSE_PROJECT_NAME=intellidoc
            - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
            - CLUSTER_NAME=docker-cluster
            - xpack.security.enabled=false
        mem_limit: 2g
        networks:
            intellidoc_network:
                ipv4_address: 10.0.0.1
    scripts:
        build:
            context: .
            dockerfile: src/Dockerfile
        environment:
            - TERM=xterm
        mem_limit: 1g
        volumes:
            - ./src/import_data.json:/app/import_data.json
        networks:
            intellidoc_network:
                ipv4_address: 10.0.0.2

networks:
    intellidoc_network:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/16
                  gateway: 10.0.0.254
